### ISSUE TITLE
Card Design

### ISSUE THREAD

**Issue by julianfbeck** [pietropizzi/GridStack#1]
Great Framework,
For my App, I'm trying to recreate a similar Card design you used in the Preview Pictures for this library. Could you share the code you used to create the Card Views? Would be really Awesome

Thanks Alot!

**Comment by pietropizzi** [comment]
That's actually part of an app I started working on and I would prefer to keep that bit closed source. Sorry.

**Comment by julianfbeck** [comment]
Ok, I understand, thanks for the fast response
