### ISSUE TITLE
Height is not compact but full

### ISSUE THREAD

**Issue by ghost** [pietropizzi/GridStack#11]
The library is based on `ScrollView`, which by default is full-screen height. Is there a better way to make its height as compact as possible without manually assigning frame height?

![image](https://user-images.githubusercontent.com/47587402/84259271-96499600-ab5b-11ea-86a8-217b7ec9b090.png)

**Comment by pietropizzi** [comment]
I definitely know that GeometryReader is taking all the available space. ScrollView I am not sure, but I believe you. I am not sure how to work around that.
