### ISSUE TITLE
Index out of range when remove value of array

### ISSUE THREAD

**Issue by gusadi09** [pietropizzi/GridStack#20]
<img width="285" alt="Screen Shot 2022-05-13 at 13 48 02" src="https://user-images.githubusercontent.com/49934033/168219239-500cbb98-5bad-4d81-934f-c7626075dccf.png">

The apps was crash when I was remove a value in array, I don't know what's wrong. please check it.

Thank you

**Comment by pietropizzi** [comment]
Sorry, that is not enough context for me to go from. Please provide a detailed description of what is going on or try to fix it yourself and open a pull request. thanks.
