### ISSUE TITLE
Not all shapes are showing

### ISSUE THREAD

**Issue by Bmorrhaye** [pietropizzi/GridStack#3]
When i try to put a Circle() or Rectangle() inside the gridview these items do not show. When I add a button or text, they do show. Any idea what can be wrong? 

Btw .. When pairing the circle with text or button in a stack, both items show.

**Comment by pietropizzi** [comment]
Could you paste the exact code of what is not working so I can investigate.

**Comment by pietropizzi** [comment]
When I set a frame on the rectangle everything is working as expected.

```swift
GridStack(minCellWidth: 200, spacing: 2, numItems: 12) { index, cellWidth in
        Rectangle()
            .fill(Color.red)
            .frame(width: cellWidth, height: cellWidth * 0.5)
}
```

<img width="1086" alt="Screenshot 2019-07-14 at 11 52 35" src="https://user-images.githubusercontent.com/410305/61182006-e52a3b00-a62d-11e9-96c7-fc766a8495d8.png">

Maybe you didn't pass a `height` to the frame? The Rectangle doesn't have an implicit height, you need to pass it one.

**Comment by Bmorrhaye** [comment]
Ok, perfect ... don't know what I was doing wrong but by specifying a height, it works now. 
One issue I have now is, and forgive me maybe for not understanding the code, that the grid does not show the items next to each other. 

``` swift
struct ContentView : View {
    var body: some View {
        GeometryReader { geometry in
            GridStack(minCellWidth: geometry.size.width, spacing: 5, numItems: 4) { index, cellWidth in
                Circle()
                    .frame(width: cellWidth * 0.5, height: cellWidth * 0.5)
            }
        }
    }
}
```

![Screenshot 2019-07-14 at 03 33 33](https://user-images.githubusercontent.com/11900576/61182462-5941f000-a5e8-11e9-8ec0-9cad7a9f9406.png)

**Comment by Bmorrhaye** [comment]
Ok, got it solved now by specifying `minCellWidth: geometry.size.width * 0.4`

thanks for this !!!

**Comment by pietropizzi** [comment]
Cool.
